// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ShowHideBgremOptionsController from "./show_hide_bgrem_options_controller"
application.register("show-hide-bgrem-options", ShowHideBgremOptionsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
