// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import NewProjectFormController from "./new_project_form_controller"
application.register("new-project-form", NewProjectFormController)

import ShowHideBgremOptionsController from "./show_hide_bgrem_options_controller"
application.register("show-hide-bgrem-options", ShowHideBgremOptionsController)

import SlideshowController from "./slideshow_controller"
application.register("slideshow", SlideshowController)

import TemplateSelectController from "./template_select_controller"
application.register("template-select", TemplateSelectController)

import VideoSelectController from "./video_select_controller"
application.register("video-select", VideoSelectController)
